name: Build and Test
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]

    steps:
      - uses: actions/checkout@v2
      - name: Build using Python ${{matrix.python-version}}
        uses: actions/checkout@v2
        with:
          python-version: ${{matrix.python-version}}

      - name: install dependencies [pip]
        run:
          python -m pip install -U pip
          pip install flake8

      - name: run linter [flake8]
        run: flake8 .

      - name: run api tests [pytest]
        run: pytest -s -v 